// This file is generated by GoAdmin CLI adm.
package main

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "cars" => http://localhost:9033/admin/info/cars
// "client" => http://localhost:9033/admin/info/client
// "client_evaluation" => http://localhost:9033/admin/info/client_evaluation
// "client_profile" => http://localhost:9033/admin/info/client_profile
// "client_rating_view" => http://localhost:9033/admin/info/client_rating_view
// "images" => http://localhost:9033/admin/info/images
// "order" => http://localhost:9033/admin/info/order
// "payment" => http://localhost:9033/admin/info/payment
// "payment_details_view" => http://localhost:9033/admin/info/payment_details_view
// "tariff" => http://localhost:9033/admin/info/tariff
//
// example end
var Generators = map[string]table.Generator{

	"cars":                 GetCarsTable,
	"client":               GetClientTable,
	"client_evaluation":    GetClientevaluationTable,
	"client_profile":       GetClientprofileTable,
	"client_rating_view":   GetClientratingviewTable,
	"images":               GetImagesTable,
	"order":                GetOrderTable,
	"payment":              GetPaymentTable,
	"payment_details_view": GetPaymentdetailsviewTable,
	"tariff":               GetTariffTable,

	// generators end
}
